apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workout-api
  template:
    metadata:
      labels:
        app: workout-api
    spec:
      containers:
      - name: workout-api
        image: ghcr.io/eswan18/workout-api:latest
        ports:
        - containerPort: 8000
        env:
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: application-secrets
                key: APP_SECRET
          - name: USER_CREATION_SECRET
            valueFrom:
              secretKeyRef:
                name: application-secrets
                key: USER_CREATION_SECRET
          - name: POSTGRES_USER
            value: {{ .Values.global.postgresql.auth.username }}
          - name: DATABASE_URL
            value: "postgresql://{{ .Values.global.postgresql.auth.username }}:{{ .Values.global.postgresql.auth.password }}@{{ .Release.Name }}-{{ .Values.postgresql.nameOverride }}.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.global.postgresql.auth.database }}"